### PR TITLE
Add info for 8723bs wifi/bt module

### PR DESCRIPTION
**Pull request by Simon-L**
Module 8723bs must be loaded to get wifi/bt to work.

### CODE REVIEW

**Comment by ThomasKaiser** [comment]
We agreed a while ago to not put such details on the **download** page since there only relevant information needed for download/decision should be present (no more walls of text people get lost into)

I addedd `8723bs` module to default module list with https://github.com/igorpecovnik/lib/commit/b6020c3fb565d53c1455bbb0ed5181c71505186b and also detailed board information is written (but yet not available) at https://github.com/igorpecovnik/lib.docs/tree/master/docs/board_details

@igorpecovnik can you please re-link 'Hardware details' on download pages for Pine64, ODROID C1 and C2 to the respective pages below `lib.docs/docs/board_details`?

**Comment by Simon-L** [comment]
Oh! I didn't realise the same file was also used in the download page, I thought I was editing the Hardware details section about Pine64 in the docs. Then it makes sense and thank you for adding the module :)

Should I close this PR?

Great to know about that other page too, good to have all these informations.

*Off-topic: I must confess many people got excited about Pine64, it really was a crazy Kickstarter project, they got much more support and interest than what they had planned, for the better... and seemingly for the worse as well given some of the issues that appeared.*

**Comment by ThomasKaiser** [comment]
Let's wait until @igorpecovnik re-links 'Hardware details' to the board details page ;)

BTW: In case you come up with a working BT solution that integrates into Armbian please feel free to discuss/present over at http://forum.armbian.com/index.php/forum/11-other-boards/

**Comment by igorpecovnik** [comment]
@ThomasKaiser 
Done. I haven't found time to make this editing simpler yet.

**Comment by ThomasKaiser** [comment]
Closing since documentation has been updated appropriately. Thanks.

**Pull request closed without merging**
